# Generated by Django 3.1.7 on 2021-04-23 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50)),
                ('seat_capacity', models.IntegerField(default=500)),
                ('wireless', models.BooleanField()),
                ('entertainment', models.BooleanField()),
                ('restoration', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.TextField(choices=[('M.', 'Mr'), ('Mme.', 'Mme')])),
                ('date_birth', models.DateField()),
                ('email', models.EmailField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default='', max_digits=19)),
                ('flight_number', models.IntegerField(default=1)),
                ('name', models.CharField(default=models.IntegerField(default=1), max_length=100)),
                ('date', models.DateField()),
                ('hour_d', models.TimeField(blank=True, null=True)),
                ('hour_a', models.TimeField(blank=True, null=True)),
                ('duration', models.DurationField(help_text='Duration for flight in hh:mm:ss format')),
                ('arrival', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='arrival', to='airline.airport')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airline.company')),
                ('departure', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='departure', to='airline.airport')),
                ('plane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airline.plane')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_resa', models.DateField(auto_now_add=True, null=True)),
                ('passenger', models.CharField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airline.user'), max_length=100)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airline.flight')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airline.user')),
            ],
        ),
    ]
